### ISSUE TITLE
Support Amazon S3

### ISSUE THREAD

**Issue by FantasticFiasco** [FantasticFiasco/aws-signature-version-4#1]
This package does not support [Amazon S3](https://aws.amazon.com/s3/) (Simple Storage Service). The decision for excluding S3 is based on the fact that it is a unique service when it comes to Signature Version 4, with exceptions to the rules of the signing algorithm.

Please give a thumbs up for this feature if you are requiring support for S3, and with enough votes, it will be implemented.

**Comment by sebastianbk** [comment]
Hi @FantasticFiasco. I am very interested in S3 support. Any chance you would have some time to discuss what would be required to implement this feature? I would love to help out with the development.

**Comment by FantasticFiasco** [comment]
Hi @sebastianbk!

I'm not sure regarding the changes required. Some of the steps described in [Signing AWS requests with Signature Version 4](https://docs.aws.amazon.com/general/latest/gr/sigv4_signing.html) are mentioning the exceptions for S3, but I'll guess one would have to try it to figure it out.

What you definitely can help me with right now are the requirements. I'm currently only supporting authentication via the headers, but it seems common to access S3 resources using [presigned urls](https://docs.aws.amazon.com/general/latest/gr/sigv4-add-signature-to-request.html). Would you like that as well? Can you also maybe tell me how you solve the issue at the moment. Do you have a workaround for it?

**Comment by FantasticFiasco** [comment]
S3 is now supported in [v1.3.0](https://www.nuget.org/packages/AwsSignatureVersion4/1.3.0), thanks for being vocal about its necessity!
