### ISSUE TITLE
Example Request: use with retrieving credentials from running instance

### ISSUE THREAD

**Issue by slikk66** [FantasticFiasco/aws-signature-version-4#231]
Hi! I'm being tasked with providing some examples for showing signature requests in multiple languages for our dev teams since I'm the one who suggested we use signed API-GATEWAY requests for a new project :)

This led me to find this package as .NET AWS SDK does not apparently have its own.

In our use case (and I imagine many others) the credentials used to sign the request will be coming from the running role of ec2/eks/ecs/lambda etc.

I've been looking for an example on .NET of how to retrieve the running instance session credentials but not having much luck.

If you could provide an example on how to sign using this package and the IAM ROLE provided credentials that would help me (and I assume many ohters!) out quite a bit.

Thanks!

**Comment by FantasticFiasco** [comment]
> ...since I'm the one who suggested we use signed API-GATEWAY requests for a new project :)

Lol, yeah that's often the way of it. Even though the first thought is _"I should've had my mouth shut"_, it positions you for advancement given you do a good job.

To minimize creating AWS resources on my end, I think I can provide you with a sample running on Lambda to show you the gist of it. Would that work for you?

**Comment by FantasticFiasco** [comment]
I forgot how bad C# integrates with Lambda. I've updated `README.md` with a new chapter about credentials. It doesn't provide you with any samples, but you'll be going in the right direction after reading the chapter.

Best of luck with your assignment!
