### ISSUE TITLE
Default Request Headers are double added on Android

### ISSUE THREAD

**Issue by daniel-rck** [FantasticFiasco/aws-signature-version-4#28]
**Describe the bug**
A HttpClient with `client.DefaultRequestHeaders.Add("x-api-key", myApiKey);` is signed correctly, but the client itself adds the header twice into the request:

    "Headers": [
    {
      "Key": "x-api-key",
      "Value": [
        "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      ]
    },
    {
      "Key": "X-Amz-Date",
      "Value": [
    ...
    }

**To Reproduce**
Try this code:

    var client = new HttpClient();
    client.DefaultRequestHeaders.Add("x-api-key", accessToken);
    
    // do a random request
    var response = await client.GetAsync(requestUri, cancellationToken, regionName, serviceName, credentials);

You can see the request object before sending [here](https://github.com/FantasticFiasco/aws-signature-version-4/blob/master/src/SendAsyncExtensions.cs#L247).

Compare to the request object that is return in `response.RequestMessage`.

**Expected behavior**
The Request Header should contain the header "x-api-key" only once. Like this:

    "Headers": [
    {
      "Key": "x-api-key",
      "Value": [
        "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      ]
    },
    {
      "Key": "X-Amz-Date",
      "Value": [
    ...
    }

**Environment (please complete the following information):**
- AWS API Gateway]
- OS: Android 8.0
- .NET version: Mono.Android

**Additional context**
I have tested an .NET Core 2.1 Console application where everything runs fine.

**Comment by FantasticFiasco** [comment]
I'll be damned, I though the .NET behavior was identical on all platforms.

I'll take a look at #29, but I am currently on holiday and wont be able to release anything until tonight or tomorrow night. Is there a way for you to work around this issue until the new version is released?

**Comment by daniel-rck** [comment]
Nevermind, I'm using my own fork right now - at least until there is a fixed version released.
Thank you and keep up the good work! :)

**Comment by FantasticFiasco** [comment]
I've released a [preview on www.nuget.org](https://www.nuget.org/packages/AwsSignatureVersion4/1.0.2-sha-2b78963). Would it be possible for you to verify that this preview is working in your environment? In case it does, I will continue with releasing the official version.

**Comment by daniel-rck** [comment]
:+1: works with 1.0.2-sha-2b78963.

**Comment by FantasticFiasco** [comment]
The new official v1.0.2 is now [live on www.nuget.org](https://www.nuget.org/packages/AwsSignatureVersion4/1.0.2).

Thank you so much for reporting this issue, and good luck to you on your future development adventures!

**Comment by daniel-rck** [comment]
Thank you for the fast response and fix, all the best likewise :)
