### ISSUE TITLE
PostAsync issues

### ISSUE THREAD

**Issue by redowl5** [FantasticFiasco/aws-signature-version-4#420]
When using PostAsync we are getting the following error

"Please specify data to sign. (Parameter 'data')"

This is our code

```csharp
var credentials = new ImmutableCredentials("xxxxxxxxxxx", "xxxxxxxxxxxxxxxxx", null);
var client = new HttpClient();
var content = JsonConvert.SerializeObject(<Object>);
var stringContent = new StringContent(content, Encoding.UTF8, "application/json");

var response = await client.PostAsync(url, stringContent,
    "eu-west-2",
    "",
    credentials);
```

I'm assuming we are doing something wrong but unable to see where, grateful for any help.  Thanks,

**Comment by FantasticFiasco** [comment]
Hi @redowl5. Your fourth argument is empty, i.e. `""`. You will have to enter the service name here, e.g. `"execute-api"` for requests to API Gateway.

**Comment by FantasticFiasco** [comment]
I have validation in place for asserting that the argument isn't `null`, but should perhaps extend that to also check for the empty string.

**Comment by FantasticFiasco** [comment]
[v1.4.1 has now been released](https://www.nuget.org/packages/AwsSignatureVersion4/1.4.1) with an improved error message.
