### ISSUE TITLE
How To Mock SendAsyncExtensions.SendAsync()?

### ISSUE THREAD

**Issue by RichieRunner** [FantasticFiasco/aws-signature-version-4#450]
Since `SendAsyncExtensions.SendAsync()` is an extension method, it cannot be mocked with Moq. What is the recommendation for mocking this method in unit tests?

I tried to mock the [underlying method that is being called](https://github.com/FantasticFiasco/aws-signature-version-4/blob/579d01ecbb422d32799a2c0ee39050141abeac0c/src/SendAsyncExtensions.cs#L234-L254), but it looks like it never gets invoked when calling this extension method.
```C#
_mockHttpClient .Setup(x => x.SendAsync(It.IsAny<HttpRequestMessage>(), It.IsAny<CancellationToken>()))
```

**Comment by FantasticFiasco** [comment]
Hi @RichieRunner!

Can you tell me how you would mock the `HttpClient` in your other tests where you would do a simple `Get` or `Post`? Another question I have is what `_mockHttpClient` is in your test?

**Comment by RichieRunner** [comment]
I was able to solve this by creating a wrapper class around your Extension class and exposing `SendAsync()` as an interface method that can be mockable with Moq.
