### ISSUE TITLE
Add PatchAsync overload

### ISSUE THREAD

**Issue by mungojam** [FantasticFiasco/aws-signature-version-4#528]
**Is your feature request related to a problem? Please describe.**
One of our APIs uses `PATCH` which isn't directly supported by this library. 

**Describe the solution you'd like**
`PATCH` overload that would be very similar to the `POST` overload that already exists.

**Describe alternatives you've considered**
I'll use your `SendAsync` overload for now.

**Additional context**
I'll hopefully contribute more to this library in future, but lots going on at the moment. Thanks again for making it!

**Comment by FantasticFiasco** [comment]
Thanks for reporting it!

Let's see if the issue gets any traction, otherwise it eventually will be implemented. I think the implementation will be easy, but we also need to update the tests to accommodate for this new feature.

**Comment by FantasticFiasco** [comment]
Unfortunately the same argumentation as [this one](https://github.com/FantasticFiasco/aws-signature-version-4/issues/526#issuecomment-1059712522) prevents me from working on this issue.

**Comment by mungojam** [comment]
Don't worry about it, it's not causing me a headache at all.

At some point I may implement both to help out.
