### ISSUE TITLE
Deadlock when calling the code from an asp.net 4.8 web forms code behind

### ISSUE THREAD

**Issue by ronenfe** [FantasticFiasco/aws-signature-version-4#543]
**Describe the bug**
Deadlock when calling the code from an asp.net 4.8 web forms code behind which is a synchronous code.

**To Reproduce**
1. Create an asp.net web forms project
2. Put following code in page_load event of a default.aspx page: 
3.      var content = new StringContent("..."
                , Encoding.UTF8, "application/json");
            var request = new HttpRequestMessage
            {
                Method = HttpMethod.Post,
                RequestUri = new Uri("..."),
                Content = content,
            };
            var credentials = new ImmutableCredentials("...", "...", null);
            var client = new HttpClient();
            var response = client.SendAsync(
              request: request,
              regionName: "...",
              serviceName: "execute-api",
              credentials: credentials).ConfigureAwait(false).GetAwaiter().GetResult();
4. Code hangs

**Expected behavior**
Method should not hang

**Environment (please complete the following information):**
- AWS service [AWS API Gateway]
- OS: [Windows 10]
- .NET version: [4.8]

**Comment by FantasticFiasco** [comment]
Hi @ronenfe and thanks for reporting this.

A couple of questions helping me reproduce this:

1. Is `request` targeting a recipient that is available on the network? I.e. should the request succeed but instead hangs?
2. Does it hang forever or does it finally throw an exception?

**Comment by ronenfe** [comment]
Yes, this code works if I copy the signing code out of the nuget and put it inside my project and make all calls sync except the call for the original httpclient which I use for it .ConfigureAwait(false).GetAwaiter().GetResult() because it also doesn't have a sync send for .net 4.x Maybe adding another method for sync signing in the nuget will work. I did a pull request on the other nuget for aws singing which I was part of writing it, but the owner doesn't approve it because he thinks it's unsafe , maybe you want to implement it the same way. https://github.com/tsibelman/aws-signer-v4-dot-net/pull/37#discussion_r832547850
The code never returns from the nuget, no exception, it just get hung.

**Comment by FantasticFiasco** [comment]
I've found the bug and will start working on fixing it in the upcoming days. Thanks for reporting it!

**Comment by FantasticFiasco** [comment]
This issue has now been fixed in [v3.0.1](https://www.nuget.org/packages/AwsSignatureVersion4/3.0.1). Thank you for reporting this issue!

**Comment by ronenfe** [comment]
Confirmed to work, thanks for the fast fix.

**Comment by ronenfe** [comment]
Thank you, what solved it for us was adding .configureawait(false) to the async calls in the nuget. You can see there the pull request.
