### ISSUE TITLE
Binary content does not POST.  408 error returned.

### ISSUE THREAD

**Issue by acurrieebix** [FantasticFiasco/aws-signature-version-4#565]
Passing a binary content will return 408 from the endpoint after a long wait.

**To Reproduce**

The following code will return a 408 from the service

```
var credentials = new ImmutableCredentials("AKIA2WNEXAMPLE", "rObND507EXAMPLE", null);

var client = new HttpClient();

byte[] fileBytes = File.ReadAllBytes(@"C:\File.pdf");
MemoryStream destination = new MemoryStream(fileBytes);
destination.Seek(0, SeekOrigin.Begin);

HttpContent content = new StreamContent(destination);

content.Headers.Add("x-api-key", "apikey");

var response = await client.PostAsync(
  "https://uat-customamazonservice.domain.net/v2/extract?inpFormat=PDF",
  content: content,
  regionName: "us-east-1",
  serviceName: "execute-api",
  credentials: credentials);
```
Checking web debugging tool (e.g. fiddler) you can see the content of the request is empty.

**Expected behavior**

The request should be sent and processed.

**Desktop (please complete the following information):**

Windows 11 .net 6 console client.

**Additional context**

If you send base64 encoded StringContent rather than StreamContent, the request is successful.

The fix is to reset the stream back to the beginning.  I suggest doing this when the content hash is created by adding the following at line 30 in ContentHashcs.

```
contentStream.Seek(0, System.IO.SeekOrigin.Begin);
```

**Comment by FantasticFiasco** [comment]
Hi @acurrieebix! 

Thank you for your detailed explanation. Let me see if I can reproduce it and fix the problem.

**Comment by FantasticFiasco** [comment]
I was able to reproduce the problem. Will continue to apply the fix.

**Comment by FantasticFiasco** [comment]
I've published a new version [here](https://www.nuget.org/packages/AwsSignatureVersion4/4.0.0-beta.1). Could you please verify that it is solving your problem?

Again, thanks for the issue description. It was spot on, and thus an easy issue to fix.

**Comment by FantasticFiasco** [comment]
An official version has been release on [nuget.org](https://www.nuget.org/packages/AwsSignatureVersion4/).

**Comment by acurrieebix** [comment]
Thanks.  Sorry I’m not going to be able to verify this under pressure on other areas.  Thanks again for your quick responses.

Andrew
