### ISSUE TITLE
Usage of IHttpClientFactory won't work in scenario where HttpClient is reused over longer time than passed token is valid

### ISSUE THREAD

**Issue by TomaszCypser** [FantasticFiasco/aws-signature-version-4#692]
**Describe the bug**

In one of the projects that I am working on, I have used the approach described in https://github.com/FantasticFiasco/aws-signature-version-4#integration-with-ihttpclientfactory. Unfortunately, I believe it won't work in cases where for example I am passing a temporary token valid for a short amount of time, and the HttpClient is going to be reused after the token was expired.

**To Reproduce**

1. Register services with AwsSignatureHandlerSettings that get token valid for a limited amount of time.
2. Reuse HttpClient after the credentials passed to AwsSignatureHandlerSettings expired.

**Expected behavior**

It would be great to have some sort of refresh mechanism where we could update credentials passed to AwsSignatureHandlerSettings after a certain amount of time. 

**Actual behavior**

Calls using expired token are responded with `The security token included in the request is expired`

**Comment by FantasticFiasco** [comment]
Hi @TomaszCypser!

The class `AwsSignatureHandlerSettings` has two constructors. The second one is accepting an implementation of the abstract class [`AWSCredentials`](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/Credentials/AWSCredentials.cs). You can provide your own implementation of this abstract class, where the temporary token is updated in the class, or the other way around where the implementation is asking for a temporary token when required. But before you implement your own class make sure you've [looked at the other existing implementations](https://github.com/aws/aws-sdk-net/tree/master/sdk/src/Core/Amazon.Runtime/Credentials) of `AWSCredentials`.

**Comment by TomaszCypser** [comment]
hi @FantasticFiasco, thank you for those examples, I completely missed the option where I could pass second AWSCredentials to the constructor 😅 

I believe the issue can be closed.
