### ISSUE TITLE
Could not load file or assembly 'AwsSignatureVersion4, Version=4.0.0.0

### ISSUE THREAD

**Issue by as14692** [FantasticFiasco/aws-signature-version-4#743]
I am making API calls to Lambda function url with HttpClient in an IntegrationTestSuite. When run independently, it works fine but when I call the `IntegrationTestSuite.dll` from another project, I get the below exception
`System.IO.FileNotFoundException: 'Could not load file or assembly 'AwsSignatureVersion4, Version=4.0.0.0, Culture=neutral, PublicKeyToken=9830731f15ae0355'. The system cannot find the file specified.'`

**Comment by FantasticFiasco** [comment]
Hi @as14692! Would you be able to create a small sample application showcasing your issue?

**Comment by as14692** [comment]
Hi @FantasticFiasco ,  
Thank you for getting back. Closing the issue. I found the problem. It was unrelated to `AwsSignatureVersion4 `package
