### ISSUE TITLE
Remove unnecessary new allocation

### ISSUE THREAD

**Issue by AgusMarquezUala** [FantasticFiasco/aws-signature-version-4#781]
https://github.com/FantasticFiasco/aws-signature-version-4/blob/b8e5480f879b475167e57da123c1d6fd0947f2b0/src/AwsSignatureHandler.cs#L27

new KeyValuePair<string, IEnumerable<string>>[0] => Array.Empty<KeyValuePair<string, IEnumerable<string>>>()

**Comment by FantasticFiasco** [comment]
Hi @AgusMarquezUala! Thanks for reporting the issue, I'll look into it!

**Comment by FantasticFiasco** [comment]
The v4.0.1 version has now been released on [nuget.org](https://www.nuget.org/packages/AwsSignatureVersion4/4.0.1). Thanks for your letting me know of the issue!
